### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by kls93** [td93/B_Damage#12]
Hi All, 

It might be a good idea to add a license to RABDAM before the paper is submitted. Does anyone have any preferences? From the available options [https://choosealicense.com/](https://choosealicense.com/), and based upon what others in the group have chosen previously, I was thinking either an MIT license or a GNU General Public License, but I'm not sure what's best. (From what I can gather, most CCP4 programs tend to use either the GPL or a variant.)

Thanks,
Kathryn

**Comment by td93** [comment]
HI Kathryn,

That's probably a good idea. I don't know much about this myself but I
wonder if the Gnu LGPLv3 would be best?

"Permissions of this copyleft license are conditioned on making available
complete source code of licensed works and modifications under the same
license or the GNU GPLv3. Copyright and license notices must be preserved.
Contributors provide an express grant of patent rights.

*However, a larger work using the licensed work through interfaces provided
by the licensed work may be distributed under different terms and without
source code for the larger work."*
Sounds like what might be the case if it is to be incorporated into CCP4...

Best,
Tom

**Comment by JonnyCBB** [comment]
Great idea!

I too am not very clued up about licenses. I mostly come across MIT licenses but typically these are used for library packages.

Here's a [very good resource](https://choosealicense.com/) that explains things simply for a few licenses. Namely:

>1. **MIT**: The [MIT License](https://choosealicense.com/licenses/mit/) is a permissive license that is short and to the point. It lets people do anything they want with your code as long as they provide attribution back to you and don’t hold you liable.
>2. **GNU GPLv3**: The [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/) is a copyleft license that requires anyone who distributes your code or a derivative work to make the source available under the same terms, and also provides an express grant of patent rights from contributors to users.

Importantly it notes:
- Use **MIT** if you want something simple and permissive
- Use **GNU GPLv3** if we care about sharing improvements

FYI, the major difference between **GNU GPLv3** and **GNU LGPLv3** (from [here](https://fosswire.com/post/2007/04/the-differences-between-the-gpl-lgpl-and-the-bsd/)) is:

>The LGPL is similar to the GPL, but is more designed for software libraries where you want to allow non-GPL applications to link to your library and utilise it. If you modify the software, you still have to give back the source code, but you are allowed to link it with proprietary stuff without giving the source code to all of that back.

I guess it's ultimately one for Elspeth but I would think of it like this:
- Do I want to allow people to use RABDAM code to create something that could end up being sold commercially? If yes choose **MIT**, if not then rule out **MIT**
- Do I care if people use RABDAM, amend it, and add their own code and don't want to share their own code? If yes then choose **GNU GPLv3** otherwise, choose **GNU LGPLv3**.

Perhaps that's oversimplified a little but it helps me. With that in mind, I would agree with @td93 and go for **GNU LGPLv3**. As much as I would love for everyone to share all of their code, I think **GNU GPLv3** could prevent things like CCP4 using it for example (whether they would is another question) because CCP4 is not free for non-academic institutions (if I remember rightly). But again, I would check with Elspeth.

**Comment by kls93** [comment]
Thanks for the replies. I agree that the GNU LGPLv3 license is the best option (and Elspeth is happy with this), so I've added it in. 

(Note however that currently the GitHub page is displaying GPL rather than LGPL - I will work out how to fix this without removing the GPL text file (which apparently I am supposed to include) later.)
